version: "3.0"
services:
  web:
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    image: nginx
    command: ['nginx-debug', '-g', 'daemon off;']
    network_mode: host
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
