# Generated by Django 3.2.8 on 2021-10-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAlbum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotify_album_id', models.CharField(max_length=50, unique=True)),
                ('album_name', models.CharField(max_length=200)),
                ('album_cover', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotify_user_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotify_track_id', models.CharField(max_length=50, unique=True)),
                ('position_in_album', models.IntegerField()),
                ('related_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='spotify.spotifyalbum')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotify_playlist_id', models.CharField(max_length=50, unique=True)),
                ('back_to_back', models.BooleanField()),
                ('enabled', models.BooleanField()),
                ('last_snapshot', models.CharField(max_length=100)),
                ('playlist_name', models.CharField(max_length=200)),
                ('playlist_picture', models.BinaryField(blank=True, null=True)),
                ('albums_included', models.ManyToManyField(to='spotify.SpotifyAlbum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.spotifyuser')),
            ],
        ),
    ]
